name: Deploy to Glitch

on:
   push:
      branches:
         - main

jobs:
   deploy:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout Repository
           uses: actions/checkout@v3
           with:
              fetch-depth: 0

         - name: Install Git
           run: sudo apt-get install git -y

         - name: Push to Glitch
           run: |
              git config --global user.email "vedivero73@gmail.com"
              git config --global user.name "vedivero"
              git remote add glitch "https://${{ secrets.GLITCH_TOKEN }}@api.glitch.com/git/shopping-mall"
              git push --force glitch main:master
              curl -X POST "https://api.glitch.com/projects/shopping-mall/restart"

         - name: Force Refresh on Glitch
           run: |
              curl -X GET "https://shopping-mall.glitch.me/__refresh"
